/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: auction/v1/genesis.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../gogoproto/gogo";
import * as dependency_2 from "./params";
import * as dependency_3 from "./auction";
import * as pb_1 from "google-protobuf";
export namespace auction.v1 {
    export class GenesisState extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            params?: dependency_2.auction.v1.Params;
            active_period?: dependency_3.auction.v1.AuctionPeriod;
            active_auctions?: dependency_3.auction.v1.Auction[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("params" in data && data.params != undefined) {
                    this.params = data.params;
                }
                if ("active_period" in data && data.active_period != undefined) {
                    this.active_period = data.active_period;
                }
                if ("active_auctions" in data && data.active_auctions != undefined) {
                    this.active_auctions = data.active_auctions;
                }
            }
        }
        get params() {
            return pb_1.Message.getWrapperField(this, dependency_2.auction.v1.Params, 1) as dependency_2.auction.v1.Params;
        }
        set params(value: dependency_2.auction.v1.Params) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_params() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get active_period() {
            return pb_1.Message.getWrapperField(this, dependency_3.auction.v1.AuctionPeriod, 2) as dependency_3.auction.v1.AuctionPeriod;
        }
        set active_period(value: dependency_3.auction.v1.AuctionPeriod) {
            pb_1.Message.setWrapperField(this, 2, value);
        }
        get has_active_period() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get active_auctions() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_3.auction.v1.Auction, 3) as dependency_3.auction.v1.Auction[];
        }
        set active_auctions(value: dependency_3.auction.v1.Auction[]) {
            pb_1.Message.setRepeatedWrapperField(this, 3, value);
        }
        static fromObject(data: {
            params?: ReturnType<typeof dependency_2.auction.v1.Params.prototype.toObject>;
            active_period?: ReturnType<typeof dependency_3.auction.v1.AuctionPeriod.prototype.toObject>;
            active_auctions?: ReturnType<typeof dependency_3.auction.v1.Auction.prototype.toObject>[];
        }): GenesisState {
            const message = new GenesisState({});
            if (data.params != null) {
                message.params = dependency_2.auction.v1.Params.fromObject(data.params);
            }
            if (data.active_period != null) {
                message.active_period = dependency_3.auction.v1.AuctionPeriod.fromObject(data.active_period);
            }
            if (data.active_auctions != null) {
                message.active_auctions = data.active_auctions.map(item => dependency_3.auction.v1.Auction.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                params?: ReturnType<typeof dependency_2.auction.v1.Params.prototype.toObject>;
                active_period?: ReturnType<typeof dependency_3.auction.v1.AuctionPeriod.prototype.toObject>;
                active_auctions?: ReturnType<typeof dependency_3.auction.v1.Auction.prototype.toObject>[];
            } = {};
            if (this.params != null) {
                data.params = this.params.toObject();
            }
            if (this.active_period != null) {
                data.active_period = this.active_period.toObject();
            }
            if (this.active_auctions != null) {
                data.active_auctions = this.active_auctions.map((item: dependency_3.auction.v1.Auction) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_params)
                writer.writeMessage(1, this.params, () => this.params.serialize(writer));
            if (this.has_active_period)
                writer.writeMessage(2, this.active_period, () => this.active_period.serialize(writer));
            if (this.active_auctions.length)
                writer.writeRepeatedMessage(3, this.active_auctions, (item: dependency_3.auction.v1.Auction) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GenesisState {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GenesisState();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.params, () => message.params = dependency_2.auction.v1.Params.deserialize(reader));
                        break;
                    case 2:
                        reader.readMessage(message.active_period, () => message.active_period = dependency_3.auction.v1.AuctionPeriod.deserialize(reader));
                        break;
                    case 3:
                        reader.readMessage(message.active_auctions, () => pb_1.Message.addToRepeatedWrapperField(message, 3, dependency_3.auction.v1.Auction.deserialize(reader), dependency_3.auction.v1.Auction));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GenesisState {
            return GenesisState.deserialize(bytes);
        }
    }
}
